# csv to json

> Original Author: Joseph P. Vantassel

> Edited by Cheng-Hsi Hsiao

Convert cleaned `.csv` data to `.json`.

In [1]:
import json
import math
import pandas as pd

In [2]:
fname = "2024_fall_members"
#fname = "2020_member_responses_clean"
df = pd.read_csv(fname + ".csv")
df.head()

,Timestamp,First Name,Last Name,UT EID,UT email address,What program are you in?,What country are you from?,State (if applicable),City,Birth Date,Personal Photo,Bio Link,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,8/31/24 12:35,Cheng-Hsi,Hsiao,ch49826,chhsiao@utexas.edu,PhD,Taiwan,NaN,Taipei,8-Sep,https://drive.google.com/open?id=1Sr8iLAPA0yqU...,https://www.linkedin.com/in/cheng-hsi-hsiao/,NaN,NaN,NaN,NaN,NaN,NaN
1,8/30/24 15:15,Shuyi,Zhang,sz9898,shuyi_zhang@utexas.edu,PhD,China,NaN,Ganzhou,24-Oct,https://drive.google.com/open?id=1EdwSEMUYpm0v...,https://www.linkedin.com/in/shuyi-zhang-a50434...,NaN,NaN,NaN,NaN,NaN,NaN
2,8/30/24 16:07,Taylor,Stinson,gts736,tstinson@utexas.edu,PhD,United States,Tennessee,Clarksville,12-Mar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,8/30/24 17:15,Omar,Abukassab,ota328,oakassab@utexas.edu,MSc & PhD,Jordan,NaN,Irbid,18-Aug,https://drive.google.com/open?id=1U-1BJNO8X5Of...,https://www.linkedin.com/in/omar-abukassab-658...,NaN,NaN,NaN,NaN,NaN,NaN
4,8/30/24 17:50,Leila,Roshanali,lr34966,leila.roshanali@utexas.edu,MS,Iran,NaN,Shiraz,16-Jun,NaN,https://www.linkedin.com/in/leila-roshanali/,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# create a clean version df
# remove space
df['First Name'].replace(' ', '', regex=True, inplace=True)
df['Last Name'].replace(' ', '', regex=True, inplace=True)
df['name'] = df['First Name'] + " " + df['Last Name']
df.rename(columns={'What program are you in?':'degree',
                   'What country are you from?':'country',
                   'State (if applicable)':'state',
                   'City':'city',
                   'Bio Link':'link'}, inplace=True)
df = df[['name','degree','country','state','city','link']]
df.sort_values(by=['name'], inplace=True)
df

,name,degree,country,state,city,link
23,A.Mert Kavala,MSc & PhD,Turkey,NaN,Istanbul,https://www.linkedin.com/in/mertkavala
16,AbhilashReddy Goli,MS,India,NaN,Hyderabad,https://www.linkedin.com/in/abhilash-reddy-gol...
22,Adityo Andikaputra,MS,Indonesia,NaN,Bandung,linkedin.com/in/adityoandikaputra
17,Ahmed Alsadah,MS,Saudi Arabia,Eastern province,Safwa - Qatif,NaN
25,Ajay Rajupalem,MS,India,NaN,Hyderabad,NaN
5,Ashray Saxena,PhD,India,NaN,Aligarh,NaN
20,Bartik Pandel,PhD,India,NaN,Jaipur,NaN
0,Cheng-Hsi Hsiao,PhD,Taiwan,NaN,Taipei,https://www.linkedin.com/in/cheng-hsi-hsiao/
7,Chenghao Bai,PhD,China,NaN,Anqing,https://www.linkedin.com/in/chenghao-bai-8168b...
19,Chih-Yu Tung,PhD,TAIWAN,NaN,Taichung,NaN
12,DesiNur Marlina,MS,Indonesia,NaN,Bandung,https://www.linkedin.com/in/desi-nur-marlina-b...
27,Faik Cuceoglu,Visiting Research Scholar,Turkiye,NaN,Ankara,https://www.linkedin.com/in/faik-c%C3%BCceo%C4...
11,Faisal Alotaibi,PhD,Saudi Arabia,NaN,Riyadh,https://www.linkedin.com/in/faisal-alotaibi-52...
29,Griffin Berse,MSc & PhD,USA,FL,Jacksonville,NaN
28,Jihwan Lee,PhD,South Korea,NaN,Gwangju,NaN
18,Juan Ortega,MS,Colombia,NaN,Bogotá,https://www.linkedin.com/in/juan-ortega-5b6581...
9,KowshikKumar Thalluru,MS,India,Andhra Pradesh,Nellore,https://www.linkedin.com/in/kowshik-kumar?utm_...
4,Leila Roshanali,MS,Iran,NaN,Shiraz,https://www.linkedin.com/in/leila-roshanali/
6,Mahsa Nia,PhD,Iran,NaN,Tehran,NaN
21,Mehmet Turkezer,PhD,Turkiye,NaN,Ankara,https://www.linkedin.com/in/mturkezer/
8,Miles Drazkowski,PhD,United States,Oregon,Willamina,www.linkedin.com/in/miles-drazkowski-ei-eit-a8...
26,NaveenRaj Manoharan,PhD,India,Tamilnadu,Erode,https://www.linkedin.com/in/naveen-raj-m
3,Omar Abukassab,MSc & PhD,Jordan,NaN,Irbid,https://www.linkedin.com/in/omar-abukassab-658...
1,Shuyi Zhang,PhD,China,NaN,Ganzhou,https://www.linkedin.com/in/shuyi-zhang-a50434...
13,Stepan Tretiakov,MSc & PhD,Russia,NaN,Kurgan,Coming Soon
10,Sujin Park,PhD,South Korea,NaN,Seoul,https://drive.google.com/file/d/1rU4EhGuV3PVtx...
2,Taylor Stinson,PhD,United States,Tennessee,Clarksville,NaN
15,Venkataraman Ramesh,PhD,India,Tamil Nadu,Trichy,https://www.linkedin.com/in/venkataraman-ramesh/
24,Willa Egan,PhD,USA,Maine,Bangor,NaN
14,Yagizer Yalcin,PhD,Turkey,NaN,Ankara,https://www.linkedin.com/in/yagizeryalcin

In [4]:
path = "images/members/"
members = []
for index, line in df.iterrows():
    name, degree, country, state, city, link = line
    split_name  = name.split(" ")

    fname = split_name[0].lower()
    for _name in split_name[1:]:
        fname += "_" + _name.lower()
    fname += ".jpg"
    
    if isinstance(state, (float)):
        if math.isnan(state):
            state = ''
    if isinstance(city, (float)):
        if math.isnan(city):
            city = ''
    if isinstance(link, (float)):
        if math.isnan(link):
            link = None

    members.append({"name":name, "path":path + fname, "degree":degree, "country":country, "state":state, "city":city, "link":link})
        
with open("members.json", "w") as f:
    json.dump(members, f, indent=4)

In [5]:
# load faculty json
with open("../../faculty.json", "r") as f:
    faculty = json.load(f)

In [6]:
# merge faculty and members
members = faculty + members
# sort by name
members = sorted(members, key=lambda x: x["name"])
# save to members.json
with open("members.json", "w") as f:
    json.dump(members, f, indent=4)
print("done")

done

In [ ]:
# overwrite the members.json file
#with open("members.json", "w") as f:
#    json.dump(members, f, indent=4)